//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppLaba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int ID { get; set; }
        public string Title1 { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
